name: Update Test Text File

on:
  push:
    branches:
      - main  # テストを実行するブランチを指定

jobs:
  update-test-text:
    runs-on: ubuntu-latest  # 使用するランナーのイメージを指定

    steps:
    - name: Checkout Repository  # リポジトリをチェックアウト
      uses: actions/checkout@v2

    - name: Update Test Text File  # テキストファイルを更新
      run: |
        echo "add push" >> test.txt
